version: "3"
services:
  app:
    container_name: proxy
    restart: on-failure
    build: .
    ports:
      - "80:3000"
    links:
      - "redis"
    command: bash -c "npm install && npm run server"
  redis:
    container_name: redis
    image: redis
    restart: on-failure
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data:/data